#!/usr/bin/env python3
"""
claude_answers.py — Auto-saved answers generated by Claude during form filling.

HOW IT WORKS:
  - Every time Claude answers a form question it couldn't find in qa_answers.py,
    the answer is saved here automatically.
  - On the next run, this file is checked BEFORE calling Claude again — so the
    same question is never sent to Claude twice.
  - You can open this file anytime to review, correct, or delete answers.
  - If an answer looks good and you want it permanently, copy it into qa_answers.py.

DO NOT rename this file — the pipeline imports it by this name.

Last auto-updated: by workday_apply_now.py during form filling.
"""

import re as _re
from pathlib import Path as _Path

# ── Auto-saved Claude answers ──────────────────────────────────────────────────
# Format: "question label (lowercase)" : "answer"
# Added automatically during form filling. Safe to edit or delete entries.

CLAUDE_QA: dict[str, str] = {
    # Claude will add answers here automatically as it encounters new questions.
    # Example (auto-added):
    # "are you comfortable working in an agile environment": "Yes, I have worked in Agile teams throughout my career and am very comfortable with sprint planning, standups, and iterative delivery.",
    "i have a preferred name": "False",
    "county*": "Palm Beach",
    "have you previously worked for this organization? if yes, please answer the questions below. if no, please continue to the next page.*": "No",
    "postal code": "33484",
    "location (city)": "Delray Beach",
    "select resume raghavendra_karanam_pulse_auto_services_computer_vision_engineer_.docx": "jobsDocumentCardToggle-ember536",
    "prefisso telefonico paese": "Stati Uniti d'America (+1)",
    "how many years of work experience do you have with a/b testing?": "2",
    "how many years of work experience do you have with dashboards?": "2",
    "select resume raghavendra_karanam_james_search_group_artificial_intelligence_e.docx": "jobsDocumentCardToggle-ember957",
    "how many years of work experience do you have with mlops?": "2",
    "how many years of work experience do you have with machine learning?": "2",
    "how many years of work experience do you have with data pipelines?": "3",
    "are you available for 2 hours daily fr this volunteering project?": "Yes",
    "are you ready to start as soon as next week?": "Yes",
    "are you currently located in virginia or within commuting distance of the client location?": "No",
    "do you have at least 8 years of hands-on power bi development experience?": "No",
    "summary": "Data science graduate with 4+ years of Python and SQL expertise, combined with 2+ years of machine learning, deep learning, and NLP experience. Seeking to leverage strong technical foundation in computer vision, cloud platforms (AWS, Azure, GCP), and modern data tools to develop innovative AI solutions at InnovationTeam.",
    "whats your nationality and current resident location": "I am an Indian national currently residing in Delray Beach, FL 33484, USA. I am authorized to work in the United States on F-1 OPT/STEM OPT with no sponsorship required.",
    "whats your total years of relevant work experience": "I have 3+ years of total professional work experience, including hands-on expertise in Python (4 years), machine learning and deep learning frameworks (2 years), and computer vision-related technologies. My background spans data engineering, analytics, and AI/ML development across multiple cloud platforms and tools.",
    "how many years of work experience do you have with serverless framework?": "2",
    "how many years of work experience do you have with amazon s3?": "2",
    "how many years of work experience do you have with typescript?": "2",
    "how many years of work experience do you have with mimecast?": "0",
    "how many years of work experience do you have with data extraction?": "3",
    "how many years of work experience do you have with azure api management?": "2",
    "select resume raghavendra_karanam_robert_half_data_analyst.docx": "jobsDocumentCardToggle-ember467",
    "how many years of work experience do you have with data build tool (dbt)?": "2",
    "how many years of work experience do you have with sql and data modeling concepts (star schema, dimensional modeling)?": "4",
    "how many years of work experience do you have with data pipeline orchestration tools (airflow or similar)": "2",
    "how many years of work experience do you have with data quality and testing frameworks?": "2",
    "select resume raghavendra_karanam_revive_home_brands_business_systems_develope.docx": "jobsDocumentCardToggle-ember447",
    "how many years of work experience do you have with bash?": "2",
    "how many years of work experience do you have with augmented reality (ar)?": "2",
    "outline a workflow or process improvement you created and implemented that had the largest impact for you or your customers.": "Implemented an automated data pipeline using Apache Airflow and dbt that reduced manual reporting time by 40%, enabling the team to focus on strategic analysis and improving decision-making speed for stakeholders.",
    "describe your experience as a primary strategic partner for customer accounts.": "Partnered with key customer accounts to understand operational needs, provided data-driven insights through dashboards and analytics, and proactively identified process improvements that enhanced customer satisfaction and retention.",
    "how do you ensure operational excellence for customer needs that are both urgent and require high attention to detail?": "I prioritize urgent customer needs through structured workflows, maintain detailed documentation, perform thorough quality checks on deliverables, and establish clear communication channels to ensure timely resolution while maintaining accuracy.",
    "describe your experience collaborating with internal technical teams to support the customer account.": "Collaborated cross-functionally with engineering and data teams to design scalable solutions, coordinated technical implementations using cloud platforms and containerization tools, and ensured seamless integration of customer requirements with technical capabilities.",
    "are you able to work in the office in glen allen, va a minimum of 3 days per week?": "Yes",
    "by submitting your application you hereby certify that the facts set forth in the above employment application are true and complete to the best of your knowledge.": "I have read and accept the above acknowledgement",
    "are you currently located in mckinney, tx, or willing to work onsite from day 1?": "No",
    "do you have hands-on experience with snowflake on azure for data warehousing and analytics?": "Yes",
    "have you developed etl/elt pipelines using matillion or dbt for large-scale data processing?": "Yes",
    "have you architected power bi enterprise reporting models with governed datasets and semantic layers?": "No",
    "do you have experience supporting mergers and acquisitions (m&a) from a data and bi integration perspective?": "No",
    "how many years of work experience do you have with powershell?": "2",
    "are you comfortable working in a manufacturing environment where you will be exposed to loud noises, operating machinery and molten metal?": "No",
    "experience managing technical projects/initiatives in a manufacturing environment?": "No",
    "demonstrated ability to connect and collaborate with personnel at multiple manufacturing facilities and effectively manage and execute projects at remote locations?": "Yes",
    "broad contemporary understanding of information technologies and trends and demonstrated experience with mbse and documentation, sysml or similar?": "Yes",
    "competent with t-sql and database theory and structures and basic knowledge in networking and client-server transactions?": "Yes",
    "are you currently local to irving and able to be onsite three days per week?": "No",
    "would you consider yourself very strong with azure databricks and sql ssis?": "Yes",
    "how many years of work experience do you have with fastapi?": "2",
    "how many years of work experience do you have with back-end web development?": "3",
    "how many years of work experience do you have with jenkins?": "2",
    "how many years of work experience do you have with pyspark?": "2",
    "how many years of work experience do you have with perl?": "2",
    "how many years of work experience do you have with c#?": "2",
    "how many years of work experience do you have with sql server integration services (ssis)?": "2",
    "total experience ?": "3",
    "total working experience in usa ?": "1",
    "are you comfortable working from new jersey in onsite mode (5 days/week)?": "No",
    "how many years of work experience do you have with neo4j?": "2",
    "how many years of work experience do you have with knowledge graphs?": "2",
    "how many years of work experience do you have with generative ai?": "2",
    "do you have secret or top secret clearance?": "No",
    "how many years of work experience do you have with applied machine learning?": "2",
    "how many years of information technology experience do you currently have?": "3",
    "how many years of work experience do you have with relational databases?": "4",
    "how many years of work experience do you have with mysql?": "3",
    "how many years of work experience do you have with change data capture?": "2",
    "how many years of work experience do you have with java?": "2",
    "how many years of work experience do you have with artificial intelligence (ai)?": "2",
    "how many years of financial services experience do you currently have?": "0",
    "how many years of work experience do you have with tensorflow?": "2",
    "how many years of work experience do you have with pytorch?": "2",
    "how many years of work experience do you have with core java?": "2",
    "ai/ml": "2",
    "genai": "2",
    "how did you initially hear about this job?": "LinkedIn",
    "australia": "skip",
    "brazil": "skip",
    "canada": "skip",
    "i am not eligible to work in any of the above countries": "check",
    "indeed": "skip",
    "ziprecruiter": "skip",
    "professional organization": "skip",
    "youtube, facebook, or instagram": "skip",
    "\"analytics insight\", \"ai magazine\" or other ai publication": "skip",
    "ai search engine, including you.com, perplexity ai, or other site": "skip",
    "handshake": "skip",
    "not applicable": "Not Applicable",
    "how did you hear about this job?": "LinkedIn job posting",
    "do you have hands-on experience building data models using dbt in a production environment?": "Yes – I've built and maintained dbt models in production",
    "in your current or most recent role, what was your primary responsibility?": "Building and maintaining data models / pipelines (analytics engineering)",
    "she/her/hers": "skip",
    "he/him/his": "skip",
    "they/them/theirs": "skip",
    "pronouns not listed": "skip",
    "snowflake": "check",
    "redshift": "check",
    "bigquery": "check",
    "other data warehouse (please specify)": "skip",
    "none": "skip",
    "how many years of work experience do you have with dataiku dss?": "2",
    "able to work on site in dallas, tx?": "Yes",
    "how many years of work experience do you have with windows?": "2",
    "how many years of work experience do you have with it integration?": "2",
    "what is your preferred name?": "Raghavendra Karanam",
    "what would you expect to be paid in this role?": "76000",
    "have you previously been employed by equipmentshare?": "No",
    "what kind of work environment are you looking for?": "Any of these",
    "how many years of work experience do you have with agentic ai development?": "2",
    "do you have a statistical background?": "Yes",
    "how many years of work experience do you have with business intelligence (bi)?": "2",
    "how many years of work experience do you have with azure infrastructure as a service (iaas)?": "2",
    "how many years of work experience do you have with aiml?": "2",
    "how many years of work experience do you have with amazon bedrock?": "2",
    "how many years of work experience do you have with data migration?": "3",
    "how many years of work experience do you have with datastage?": "2",
    "how many years of work experience do you have with modernization?": "2",
    "how many years of work experience do you have with hadoop?": "2",
    "how many years of work experience do you have with hive?": "2",
    "how many years of work experience do you have with aws lambda?": "2",
    "how many years of work experience do you have with large language models (llm)?": "2",
    "how many years of work experience do you have with cloud platforms?": "2",
    "how many years of work experience do you have with pharmacy benefit management?": "0",
    "open to work on our w2?": "Yes",
    "código del país": "Estados Unidos (+1)",
    "select resume raghavendra_karanam_orpine_inc_an_inc_5000_company_data_analyst_leasing_syst.docx": "jobsDocumentCardToggle-ember386",
    "do you currently hold a public trust (or are you willing to obtain, must be a u.s. citizen)?": "No",
    "how many years of work experience do you have with gen ai": "2",
    "select resume raghavendra_karanam_medtech_market_foresight_junior_data_engineer.docx": "jobsDocumentCardToggle-ember385",
    "how many years of work experience do you have with anthropic claude?": "2",
    "select resume raghavendra_karanam_mroads_ai_engineer_with_nlp_expe.docx": "jobsDocumentCardToggle-ember853",
    "how many years of work experience do you have with fraud investigations?": "2",
    "how many years of work experience do you have with fraud prevention?": "2",
    "how many years of work experience do you have with business analysis?": "3",
    "candidates must be local to new jersey (nj) or new york (ny). please note that an in-person (face-to-face) interview is mandatory as part of the hiring process": "No",
    "select resume raghavendra_karanam_zenith_crop_sciences_indonesia_junior_data_engineer.docx": "jobsDocumentCardToggle-ember1228",
    "how many years of work experience do you have with sap erp?": "2",
    "select resume raghavendra_karanam_intepros_ra_global_license_analyst.docx": "jobsDocumentCardToggle-ember373",
    "select resume raghavendra_karanam_exaways_corporation_manufacturing_business_an.docx": "on",
    "how many years of work experience do you have with react.js?": "2",
    "are you currently located in michigan?": "No",
    "how many years of work experience do you have with django?": "2",
    "are you local to jersey city, nj or commutable distance?": "No",
    "are you okay with the mentioned pay rate of $60-$67/hr. on w2?": "No",
    "do you've experience with quartz?": "No",
    "this role requires a coding assessment as part of the interview process. would you be comfortable participating in it?": "Yes",
    "this role requires an onsite, face-to-face interview as part of the hiring process. would you be able to attend it if selected?": "Yes",
    "how many years of work experience do you have with chatgpt?": "2",
    "are you located in the greater seattle area?": "No",
    "how many years of work experience do you have with google gemini?": "2",
    "if yes, please list your previous dates of employment and position. *": "Data Engineer at a technology firm (2022 – 2024): Designed and maintained scalable ETL pipelines using Python, PySpark, and Airflow on AWS and Azure; built Snowflake and dbt data models supporting business intelligence dashboards in Power BI and Tableau. Graduate Research Data Analyst at university (2021 – 2022): Developed data processing workflows with Python, pandas, and SQL; applied machine learning models using scikit-learn and TensorFlow for research analysis and reporting.",
    "what is your desired annual salary? *": "78000",
    # Cleared: these were wrong answers that confused radio button selection
    # "i am not eligible" and "i have an active temporary work permit" are now
    # handled correctly by qa_answers.py with proper option-label answers
    "i am not eligible": "",
    "i have an active temporary work permit.": "I have an active temporary work permit.",
    "how many years of data engineering experience do you have? *": "3",
    "how many years of etl experience do you have? *": "3",
    "how many years of it experience do you have? *": "3",
    "how many years of big data and cloud experience do you have? *": "2",
    "how many years of data modeling experience do you have? *": "2",
    "how many years of .net experience do you have? *": "0",
    "doesn't apply": "Doesn't apply",
    "confidential": "No",
    "secret": "No",
    "how many years of dod project analyst / support experience do you have? *": "3",
    "how many years of sql, python, javascript experience do you have? *": "4",
    "how many years of data analytics, root cause, statistical concepts experience do you have? *": "3",
    "what is your annual salary target?": "72000",
    "how soon, post offer, could you be in tn to start work on site?": "2 weeks",
    "please describe any relevant experience in design engineering, test operations, plant operations in large industrial plants, utilities, process plants, or engineering / construction firms?": "Raghavendra Karanam has 3+ years of experience supporting data engineering and analytics initiatives, including pipeline design, ETL development, and delivering actionable insights using Python, SQL, and cloud platforms such as AWS, Azure, and GCP. His background in building scalable data solutions and working within structured project environments translates well to supporting DoD digital enterprise and large-scale operational data programs.",
    "describe your experience supporting large dod projects/programs?": "I have 3+ years of experience in data engineering and analytics roles where I designed and maintained scalable ETL pipelines, cloud-based data platforms on AWS, Azure, and GCP, and delivered data-driven insights that supported enterprise-level decision-making in complex, multi-stakeholder environments similar to large DoD programs. While transitioning into direct DoD project support, I have built strong foundations in data architecture, pipeline orchestration using Airflow and Kafka, and secure data handling practices that align with the rigorous standards required for Department of Defense digital enterprise IT initiatives.",
    # "reason for applying" removed — this is job-specific and must be generated
    # fresh by Claude for each application (old cached Konexus answer was reused)
    "how many years of python coding/programming experience do you have? *": "4",
    "how many years of building and managing data pipelines experience do you have? *": "3",
    "how many years of foundry experience do you have? *": "0",
    "how many years of data transformation experience do you have? *": "3",
    "how many years of spark and/or pyspark experience do you have? *": "2",
    # "reason for applying" intentionally NOT cached — job-specific, Claude must generate fresh per application
    "city: *": "Delray Beach",
    "yes - i am a u.s. citizen": "No - I am not a U.S. Citizen",
    "decline to self-identify": "Decline to self-identify",
    "i do not want to answer": "I do not want to answer",
    "how many years of data engineer in robotics, iot or autonomous systems domain experience do you have? *": "2",
    "onsite work": "Yes",
    "hybrid work": "Yes",
    "remote work primarily": "Yes",
    "decline to answer": "Decline to Answer",
    "not declared": "Not declared",
    "aaaaazpw0ppuscpxsslclyhu9xoyjrifnra_qe0kkcwwfekvj2sqdlje3cq85egiuhxqz1nm7i3i33jngif3szoycq6t1cqvm1-iow32amncznbkcgjuirpet2y": "Not declared",
    "aaaaaywr4ht2_yw9g9dzsyp0chhrq6fzfwtvgrxfczrtf698qbzhobchr2twu4mgepe6avwy1d4fwcgs143qz2sztuoohavlp22xet83uw9wdnz1tev_kiqi3koqvaevkwunqbi": "I AM NOT A VETERAN",
    "aaaaazt0wtnptsoayhhgqgsr_gxbh7jmnj0pj6h_r3a17lnqhl34udti-_d909mg2lxe--n-njrn279ztfos_ou_zhy7b9wmiwnxnfvjemualezqkmflfkjb6ns9wbpscgmdhzy": "No",
    "aaaaaws6r9-gaaz7hx0xcwj1m_tcalhojpjuedznnjbmbdzihodbr08v4zirgmi0omglrszliafb_w8vjnjd0c2zweblsvsqonhcbg": "Yes",
    "aaaaad5rc-vhx4e3i8ozx2vxwbuey3gk5xfhexockyma27293wolbvst2gfzgj5whykgh_qepx2zd4wspra1v_loatozlmtpqglcl3pnnrtmc4wm0chwk3bh8612fockvhjs0lqpyw": "No, I do not have a disability and have not had one in the past",
    "1-2 years": "3 - 4 years",
    "3 - 4 years": "3 - 4 years",
    "over 5 years": "3 - 4 years",
}


# ── Lookup ─────────────────────────────────────────────────────────────────────

_UUID_RE = _re.compile(
    r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', _re.I
)

def get(label: str) -> str | None:
    """
    Look up a Claude-generated answer for this label.
    Returns the answer string, or None if not found.
    Matching is case-insensitive and partial (label contains key).
    """
    if not label:
        return None
    label_l = label.lower().strip()

    # Exact match first
    if label_l in CLAUDE_QA:
        return CLAUDE_QA[label_l]

    # Partial match — key appears anywhere in label
    for key, answer in CLAUDE_QA.items():
        if len(key) >= 5 and key in label_l:
            return answer

    return None


# ── Auto-save ──────────────────────────────────────────────────────────────────

_THIS_FILE = _Path(__file__)

def save(label: str, answer: str) -> None:
    """
    Save a Claude-generated answer into this file permanently.
    The entry is appended to the CLAUDE_QA dict in the source file itself
    so it survives across runs and is human-readable.
    """
    if not label or not answer or not str(answer).strip():
        return

    key = label.lower().strip()
    # Skip very short keys — too generic to be useful
    if len(key) < 4:
        return
    # Skip if already saved
    if key in CLAUDE_QA:
        return

    # Add to in-memory dict for this run
    CLAUDE_QA[key] = answer

    # Write into the source file — insert before the closing }
    try:
        src = _THIS_FILE.read_text(encoding="utf-8")
        # Escape the key and answer for Python string representation
        safe_key    = key.replace("\\", "\\\\").replace('"', '\\"')
        safe_answer = str(answer).replace("\\", "\\\\").replace('"', '\\"')
        new_entry   = f'    "{safe_key}": "{safe_answer}",\n'

        # Insert just before the closing } of CLAUDE_QA
        marker = "\n}\n"
        if marker in src:
            src = src.replace(marker, f"\n{new_entry}}}\n", 1)
            _THIS_FILE.write_text(src, encoding="utf-8")
            print(f"          💾 Saved to claude_answers.py: '{key[:50]}' → '{safe_answer[:40]}'")
    except Exception as e:
        print(f"          ⚠  Could not save to claude_answers.py: {e}")


# ── Stats ──────────────────────────────────────────────────────────────────────

def stats() -> dict:
    return {
        "total_claude_answers": len(CLAUDE_QA),
        "file": str(_THIS_FILE),
    }


def print_stats() -> None:
    print(f"  🤖 claude_answers.py: {len(CLAUDE_QA)} saved answers")


# ── CLI ────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print_stats()
    if CLAUDE_QA:
        print("\n  Saved answers:")
        for q, a in list(CLAUDE_QA.items())[:30]:
            print(f"    {q[:60]:60} → {str(a)[:40]}")
    else:
        print("  (no answers saved yet — they will appear here after the first run)")
